#Pick combiler, in this case the clang compiler
#sudp apt-get install clang 
CC := clang
#Set the flags for the compiler
CFLAGS := `sdl2-config --libs --cflags` -O0 --std=c99 -Wall -lm
#Add eventual headers here
HDRS := 
#Source file to compile
SRCS := mandelbrotZoom.c
#Generate names of object files
OBJS := $(SRCS:.C=.o)
#Pick a name for the executable that is generated by the compiler
EXEC := mandelbrotZoom
#default recipie
all: $(EXEC)